[package]
name = "mqtt_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0.6.0", features = ["codec"] }
protocol = {path = "../protocol"}
tokio = { version = "1", features = ["full"] }
futures = "0.3"