[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5"
tokio-util = { version = "0.6.0", features = ["codec"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"